### PR TITLE
PR for code review of milestone 3 - Styling

### PR DESCRIPTION
**Pull request by dili021**
- Buttons receive width and color as props.
- Zero is double width of the rest.
- Right column is orange by default.
- Flexbox used throughout.

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @dili021  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Let's make your repo looks professional by applying all the 3 basic rules, kindly update your `README` file and remove unnecessary content**.
Checkout out the below link for help, free free to follow this [template](https://github.com/microverseinc/readme-template) from pathwright

image

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by dili021** [comment]
As the milestones haven't mentioned anything about the readme, which they usually do, I have left it for the last one. The readme can be found on the PR for milestone 5

**Comment by bellom** [comment]
Ohh!
In another word;  seems I made a mistake then, I should have marked the PR as invalid, cause code reviewer might not check the rest of the PR's created, I will suggest you copy and paste then.

If your next PR is not having a professional README file, it might be marked as invalid.

**Comment by dili021** [comment]
Done

**Review by Oghenebrume50 — APPROVED** [review]
### APPROVED

@dili021 Kudos for making changes and updating the readme this is an important part of your project, please merge and  move on **This is approved**

**RAPHAEL NORIODE** :mask: STAY_SAFE

**Pull request merged**
